// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DocumentLanguage", b =>
                {
                    b.Property<string>("CelexNumber")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("character varying(3)");

                    b.HasKey("CelexNumber", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("DocumentLanguages");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("LanguageCode");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageCode = "BG",
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageCode = "HR",
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageCode = "CS",
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageCode = "DA",
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageCode = "NL",
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageCode = "EN",
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageCode = "ET",
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageCode = "FI",
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageCode = "FR",
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageCode = "DE",
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageCode = "EL",
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageCode = "HU",
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageCode = "GA",
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageCode = "IT",
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageCode = "LV",
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageCode = "LT",
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageCode = "MT",
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageCode = "PL",
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageCode = "PT",
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageCode = "RO",
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageCode = "SK",
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageCode = "SL",
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageCode = "ES",
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageCode = "SV",
                            LanguageName = "Swedish"
                        });
                });

            modelBuilder.Entity("Domain.Entities.LawDocument", b =>
                {
                    b.Property<string>("Celex")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Type")
                        .HasColumnType("character(1)");

                    b.HasKey("Celex");

                    b.HasIndex("Celex")
                        .IsUnique();

                    b.ToTable("LawDocuments");
                });

            modelBuilder.Entity("Domain.Entities.DocumentLanguage", b =>
                {
                    b.HasOne("Domain.Entities.LawDocument", "LawDocument")
                        .WithMany("DocumentLanguages")
                        .HasForeignKey("CelexNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Language", "Language")
                        .WithMany("DocumentLanguages")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LawDocument");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Navigation("DocumentLanguages");
                });

            modelBuilder.Entity("Domain.Entities.LawDocument", b =>
                {
                    b.Navigation("DocumentLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
