services:
  # PostgreSQL Database (for both app and auth data)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${APP_DB_NAME},${AUTH_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    ports:
      - "5433:5432"
    networks:
      - app-network
  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__AppConnection=Host=postgres;Database=${APP_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__AuthConnection=Host=postgres;Database=${AUTH_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=http://localhost:8000
      - Jwt__Audience=http://localhost:8000
      - ConnectionStrings__AzureStorage=${AZURE_BLOB_CONNECTION}
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "8000:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

# Data persistence
volumes:
  postgres_data:
  redis_data:

# Network for service communication
networks:
  app-network:
    driver: bridge
